module.exports = {
	authService: require("./auth.service"),
	userService: require("./user.service"),
	categoryService: require("./category.service"),
	userCollectionService: require("./userCollection.service"),
	userTokenService: require("./userToken.service"),
	customService: require("./custom.service"),
	activityService: require("./activity.service"),
	assignedTokenService: require("./assignedToken.service"),
	auctionService: require("./auction.service"),
	auctionOfferService: require("./auctionOffer.service"),
	userFavoritesService: require("./userFavorites.service"),
	userFollowService: require("./userFavorites.service"),
	userFollowLikeService: require("./userFollowLike.service"),
	settingService: require("./setting.service"),
	subscribeService: require("./subscribe.service"),
	eventService: require("./event.service"),
};
